export const constants = {
  ADD_TO_FAV: "ADD_TO_FAV",
  REMOVE_FRM_FAV: "REMOVE_FRM_FAV",
  POKE_URL: "POKE_URL",
  RUN_API: "RUN_API",
  POKE_DATA: "POKE_DATA",
  PRE_URL: "PRE_URL",
  PARTICULAR_POKO: "PARTICULAR_POKO",
  ADD_FAV_FRM_FIREBASE: "ADD_FAV_FRM_FIREBASE",
  IS_ADDED_FAV_FRM_FIREBASE: "IS_ADDED_FAV_FRM_FIREBASE",
};
